### ISSUE TITLE
Can't post messages concurrently

### ISSUE THREAD

**Issue by benjamin-hodgson** [iancooper/Paramore#132]
We get intermittent errors logged in production when multiple threads (API requests) try to POST a message at the same time. The error is `System.NotSupportedException: Pipelining of requests forbidden`.

```
Polly.CircuitBreaker.BrokenCircuitException: The circuit is now open and is not allowing calls.
---> System.NotSupportedException: Pipelining of requests forbidden
   at paramore.brighter.commandprocessor.messaginggateway.rmq.ConnectionPolicyFactory.<>c__DisplayClass4.<.ctor>b__1(Exception exception, TimeSpan timeSpan, Context context)
   at Polly.Retry.RetryPolicyStateWithSleep.CanRetry(Exception ex)
   at Polly.Retry.RetryPolicy.Implementation(Action action, IEnumerable`1 shouldRetryPredicates, Func`1 policyStateFactory)
   at Polly.CircuitBreaker.CircuitBreakerPolicy.Implementation(Action action, IEnumerable`1 shouldRetryPredicates, ICircuitBreakerState breakerState)
   at paramore.brighter.commandprocessor.messaginggateway.rmq.RmqMessageProducer.Send(Message message, Int32 delayMilliseconds)
   at paramore.brighter.commandprocessor.CommandProcessor.<>c__DisplayClass1`1.<Post>b__0()
   at Polly.Retry.RetryPolicy.Implementation(Action action, IEnumerable`1 shouldRetryPredicates, Func`1 policyStateFactory)
   at Polly.CircuitBreaker.CircuitBreakerPolicy.Implementation(Action action, IEnumerable`1 shouldRetryPredicates, ICircuitBreakerState breakerState)
   at paramore.brighter.commandprocessor.CommandProcessor.Post[T](T request)

... (Huddle-specific stack trace snipped) ...
```

It's a concurrency issue, so it's obviously quite difficult to reproduce/debug. That said, here's a failing test case which reproduces the exception pretty consistently for me:

```csharp
    [Subject("Messaging Gateway")]
    [Tags("Requires", new[] { "RabbitMQ", "RabbitMQProducerReceiver" })]
    public class When_multiple_threads_try_to_post_a_message_at_the_same_time
    {
        private static IAmAMessageProducer s_messageProducer;
        private static Message s_message;
        private static string s_messageBody;
        private static IDictionary<string, object> s_messageHeaders;

        private Establish _context = () =>
        {
            var logger = LogProvider.For<RmqMessageConsumer>();

            s_message = new Message(header: new MessageHeader(Guid.NewGuid(), "test1", MessageType.MT_COMMAND), body: new MessageBody("test content"));

            s_messageProducer = new RmqMessageProducer(logger);
        };

        private Because _of = () =>
        {
            // fork a bunch of threads, all of which try to send a message
            Parallel.ForEach(Enumerable.Range(0, 10), _ =>
            {
                s_messageProducer.Send(s_message);
            });
        };

        It _should_not_throw = () => { };

        private Cleanup _tearDown = () =>
        {
            s_messageProducer.Dispose();
        };
    }
```

My hypothesis is that multiple threads are attempting to write to the same socket and their requests are getting interleaved.

My proposed fix is to restrict access to the RabbitMQ channel to a single worker thread. This thread would spin on a `BlockingCollection`, pulling messages out of the collection and publishing them to Rabbit. A call to `Send` just adds the message to the `BlockingCollection`. I can work on a pull request with that in it.

**Comment by iancooper** [comment]
We're going to drop the Task on MessageProducer for now, as it was a placeholder. That means we can simplify the fix to using a critical section to protect access the the broker. When we implement the *Async versions of the CP interfaces we can address non-blocking access to the broker properly, accounting for the inability to push onto the pipeline from multiple threads simultaneously
